server {
    listen 172.20.0.3:7001;
    server_name [ONION_SERVICE_3_ADDRESS].onion;

    location / {
    # Define connection limit for this server
    limit_conn timeout_limit 10;
    
    # Set HTML content type
    add_header Content-Type text/html;
    
    # Suspicious/revealing headers
    add_header X-Forwarded-For "172.22.0.2";
    add_header X-Load-Balancer "nginx-DarkMarket-03.internal";
    
    # Set extreme timeouts
    proxy_connect_timeout 86400s;
    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;
    
    # Force extremely slow transfer
    limit_rate 25;  # Bytes per second
    limit_rate_after 10;  # Allow header to load
    
    # Serve the file with intentional delay
    root /var/www/html;
    try_files /timeout.html =404;
    }
}
