server {
    # Listen only on SSH network interface
    listen 172.22.0.2:8080;
    
    # Generic server name
    server_name _;
    
    # Document root
    root /var/www/personal;
    
    # Normal request handling
    location / {
        autoindex on;
    }
}
