user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server_tokens off;  # Hides Nginx version in Server header
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    
    # Fix shared memory zone with explicit size
    limit_conn_zone $binary_remote_addr zone=timeout_limit:10m;

    # Include HTTP configurations
    include /etc/nginx/http.d/*.conf;
}

# TCP/UDP proxy for SSH
stream {
    include /etc/nginx/stream.d/*.conf;
}
